name: SQA CI & CT Pipeline

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP Environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, json, dom, libxml, xml

    - name: Install PHP Dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Run Automated Tests
      run: |
        chmod +x vendor/bin/phpunit
        ./vendor/bin/phpunit tests/
